name: Build and Publish Docker image

on:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: outsystems/Identity-keycloak-operator

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_HUB_CLONE_TOKEN }}
      - name: Config Git
        run: |
          git config --global url."https://${{ secrets.GIT_HUB_CLONE_TOKEN }}@github.com".insteadOf "https://github.com"
      - name: Setup Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.9'
      - name: Test
        run: |
          make test
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_HUB_CLONE_TOKEN }}
      - name: Config Git
        run: |
          git config --global url."https://${{ secrets.GIT_HUB_CLONE_TOKEN }}@github.com".insteadOf "https://github.com"
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Setup Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.9'
      - name: Build and Push
        run: |
          make build
          make docker-build IMG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
